-- 판매자 주문 목록 테스트를 위한 데이터 추가

-- order_sales 테이블이 없다면 생성
CREATE TABLE order_sales (
    SALE_ORDER_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(100) NOT NULL,
    ORDER_STATUS VARCHAR2(20) DEFAULT 'ORDERED',
    ORDER_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- order_sales_items 테이블이 없다면 생성
CREATE TABLE order_sales_items (
    SALE_ORDER_ID NUMBER NOT NULL,
    SALE_ITEM_ID NUMBER NOT NULL,
    ORDER_QUANTITY NUMBER NOT NULL,
    TOTAL_PRICE NUMBER NOT NULL,
    PRIMARY KEY (SALE_ORDER_ID, SALE_ITEM_ID)
);

-- sales 테이블이 없다면 생성
CREATE TABLE sales (
    SALE_ITEM_ID NUMBER PRIMARY KEY,
    SELLER_ID VARCHAR2(100) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION CLOB,
    QTY NUMBER DEFAULT 0,
    SALE_STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 시퀀스 생성 (없는 경우)
CREATE SEQUENCE sale_order_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE sale_item_seq START WITH 1 INCREMENT BY 1;

-- 테스트용 판매 상품 데이터
INSERT INTO sales (SALE_ITEM_ID, SELLER_ID, TITLE, DESCRIPTION, QTY, SALE_STATUS, CREATED_TIME)
VALUES (sale_item_seq.NEXTVAL, 'seller001', '신선한 사과', '맛있는 사과입니다', 100, 'ACTIVE', SYSTIMESTAMP);

INSERT INTO sales (SALE_ITEM_ID, SELLER_ID, TITLE, DESCRIPTION, QTY, SALE_STATUS, CREATED_TIME)
VALUES (sale_item_seq.NEXTVAL, 'seller001', '고급 쌀', '프리미엄 쌀입니다', 50, 'ACTIVE', SYSTIMESTAMP);

-- 테스트용 주문 데이터
INSERT INTO order_sales (SALE_ORDER_ID, USER_ID, ORDER_STATUS, ORDER_DATE)
VALUES (sale_order_seq.NEXTVAL, 'buyer001', 'ORDERED', SYSTIMESTAMP);

INSERT INTO order_sales (SALE_ORDER_ID, USER_ID, ORDER_STATUS, ORDER_DATE)
VALUES (sale_order_seq.NEXTVAL, 'buyer002', 'SHIPPED', SYSTIMESTAMP);

-- 테스트용 주문 상세 데이터
INSERT INTO order_sales_items (SALE_ORDER_ID, SALE_ITEM_ID, ORDER_QUANTITY, TOTAL_PRICE)
VALUES (1, 1, 5, 25000);

INSERT INTO order_sales_items (SALE_ORDER_ID, SALE_ITEM_ID, ORDER_QUANTITY, TOTAL_PRICE)
VALUES (2, 2, 3, 15000);

-- 커밋
COMMIT;
