-- 기존 테이블 구조에 맞는 테스트 데이터 추가

-- 시퀀스 생성 (없는 경우)
CREATE SEQUENCE sale_item_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE auction_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE sale_order_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE bid_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE review_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE qna_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE image_seq START WITH 1 INCREMENT BY 1;

-- 테스트용 판매 상품 데이터
INSERT INTO sales (SALE_ITEM_ID, QTY, SALE_STATUS, JUDGE_KIND_NAME, CUT_NAME, TITLE, DESCRIPTION, WEIGHT, PRICE, GRADE, TRACEABILITY_NUM, SELLER_ID, CREATED_TIME)
VALUES (sale_item_seq.NEXTVAL, 100, 'on', '소', '등심', '소고기 등심', '신선한 소고기 등심입니다', '1kg', 25000, '1++', 'KR123456789', 'seller001', SYSTIMESTAMP);

INSERT INTO sales (SALE_ITEM_ID, QTY, SALE_STATUS, JUDGE_KIND_NAME, CUT_NAME, TITLE, DESCRIPTION, WEIGHT, PRICE, GRADE, TRACEABILITY_NUM, SELLER_ID, CREATED_TIME)
VALUES (sale_item_seq.NEXTVAL, 50, 'on', '돼지', '삼겹살', '돼지고기 삼겹살', '프리미엄 돼지고기 삼겹살입니다', '500g', 15000, '1+', 'KR987654321', 'seller001', SYSTIMESTAMP);

-- 테스트용 경매 데이터
INSERT INTO auctions (AUCTION_ID, TITLE, DESCRIPTION, AUCTION_STATUS, JUDGE_KIND_NAME, ITEM_NAME, 
                     INITIAL_PRICE, BUY_NOW_PRICE, BID_INCREMENT, START_DATE, END_DATE, AUTO_EXTEND, SELLER_ID, CREATED_TIME)
VALUES (auction_seq.NEXTVAL, '특급 쌀 경매', '최고급 쌀 경매입니다', 'ACTIVE', '쌀', '특급 쌀', 
        10000, 50000, 1000, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '7' DAY, 'N', 'seller001', SYSTIMESTAMP);

-- 테스트용 판매 주문 데이터
INSERT INTO order_sales (SALE_ORDER_ID, USER_ID, ORDER_STATUS, ORDER_DATE)
VALUES (sale_order_seq.NEXTVAL, 'buyer001', 'ORDERED', SYSTIMESTAMP);

-- 테스트용 판매 주문 상세 데이터
INSERT INTO order_sales_items (SALE_ORDER_ID, SALE_ITEM_ID, ORDER_QUANTITY, TOTAL_PRICE)
VALUES (1, 1, 5, 25000);

-- 테스트용 입찰 데이터
INSERT INTO bids (BID_ID, AUCTION_ID, USER_ID, BID_PRICE, BID_STATUS, BID_TIME, CREATED_TIME)
VALUES (bid_seq.NEXTVAL, 1, 'buyer001', 15000, 'ACTIVE', SYSTIMESTAMP, SYSTIMESTAMP);

-- 테스트용 장바구니 데이터
INSERT INTO cart (USER_ID, SALE_ITEM_ID, QUANTITY, CREATED_TIME, UPDATED_TIME)
VALUES ('buyer001', 1, 3, SYSTIMESTAMP, SYSTIMESTAMP);

-- 테스트용 리뷰 데이터
INSERT INTO reviews (REVIEW_ID, SALE_ITEM_ID, USER_ID, RATING, REVIEW_COMMENT, CREATED_TIME, UPDATED_TIME)
VALUES (review_seq.NEXTVAL, 1, 'buyer001', 5, '정말 맛있어요!', SYSTIMESTAMP, SYSTIMESTAMP);

-- 테스트용 QnA 데이터
INSERT INTO qna (QNA_ID, PRODUCT_ID, PRODUCT_TYPE, QUESTION_USER_ID, QUESTION_CONTENT, IS_ANSWERED, CREATED_TIME, UPDATED_TIME)
VALUES (qna_seq.NEXTVAL, 1, 'SALE', 'buyer001', '배송은 언제 되나요?', 'N', SYSTIMESTAMP, SYSTIMESTAMP);

-- 테스트용 상품 이미지 데이터
INSERT INTO product_images (IMAGE_ID, PRODUCT_ID, PRODUCT_TYPE, IMAGE_URL, IS_THUMBNAIL, ORDER_INDEX, CREATED_TIME)
VALUES (image_seq.NEXTVAL, 1, 'SALE', '/images/apple1.jpg', 'Y', 1, SYSTIMESTAMP);

INSERT INTO product_images (IMAGE_ID, PRODUCT_ID, PRODUCT_TYPE, IMAGE_URL, IS_THUMBNAIL, ORDER_INDEX, CREATED_TIME)
VALUES (image_seq.NEXTVAL, 1, 'SALE', '/images/apple2.jpg', 'N', 2, SYSTIMESTAMP);

COMMIT;
